### ISSUE TITLE
subscribeCandles resolution

### ISSUE THREAD

**Issue by iamzifei** [bennycode/ig-trading-api#409]
It seems like ChartResolution is not exported as an interface to the library. 

Also, when I try to use the subscribeCandles, doesn't matter which resolution value I put. It will always update on a second basis.

```
client.stream.subscribeCandles([symbol], "HOUR", (epic, data) => {
  console.log(data);
});
```

**Comment by bennycode** [comment]
Hey @iamzifei, the `ChartResolution` is exported here: https://github.com/bennycode/ig-trading-api/blob/0e700a891950df1df829b6b8a0588499f7cee1b3/src/lightstreamer/interfaces.ts#L1-L6

**Comment by franck34** [comment]
```
import { APIClient, Resolution } from 'ig-trading-api';

[...]

client.stream.subscribeCandles([epics], Resolution.SECOND, (epic, candle) => {
  console.log(epic);
  console.log(candle)
});
```
