### ISSUE TITLE
Expose httpClient on RestClient

### ISSUE THREAD

**Issue by loadpixels** [bennycode/ig-trading-api#43]
Great start on this module - the others that are floating around on the internet are massively out of date.

Since this doesn't yet have full coverage of the IG Index API, I thought it'd be a good idea expose the AxiosInstance RESTClient.httpClient to allow sending arbitrary requests to IG as a stopgap.

**Comment by bennycode** [comment]
That's a good idea. Would you mind creating a PR for that?
