### ISSUE TITLE
streamCandles never calls the update callback

### ISSUE THREAD

**Issue by krooq** [bennycode/ig-trading-api#513]
Hi! 
First off Benny I just wanna say, big thanks for putting in a massive effort to get this going, love your work!

On to business, hoping someone can help with an issue I've been having...
I've got everything working except the streaming API.
I have a demo account setup, am able to login and query the REST API all no worries.
However, when I try the streamCandles method on the streaming API the callback is never called, i.e.
```
    const client = new APIClient(url, apiKey)
    client.stream.subscribeCandles(["CS.D.AUDUSD.CFD.IP"], ChartResolution.SECOND, (epic, candle) => {
        console.log(candle) // never gets called
    })
```
Can't figure out why, the market for the EPIC is open, I've tried the streaming companion (demo account one) and it works.
Anyone run into this before?

EDIT: see PR #514

**Comment by bennycode** [comment]
Hi @krooq, thank you for taking the time filing this issue. Feedback from users is what this library lives from. I merged your suggestion (#514) and released v0.13.6. Can you please download it and report back if it fixes the issue?

Regarding fetching candles: Instead of subscribing to future candles, I would like to fetch historic candles (market data) from IG. Do you know a way how to do this?

**Comment by krooq** [comment]
I tried 0.13.6 it does indeed work!

I've been able to get historic data through the REST API
e.g. for the last 10 minutes: `const data = (await igApiClient.rest.market.price.getPrices("CS.D.AUDUSD.CFD.IP", Resolution.MINUTE, 10)).prices`
But if you want older data there is another method on the PriceAPI i.e. `getPricesBetweenDates`

**Comment by bennycode** [comment]
Great! Thank you for reporting back. I will close the issue as solved. For everyone coming here by Google search, this is the [getPricesBetweenDates function](https://github.com/bennycode/ig-trading-api/blob/baec75391e08fcd75cf4faa918f9d46dde9ef2eb/src/market/prices/PriceAPI.ts#L100C9-L100C30).
