### ISSUE TITLE
createOrderResponse freezes

### ISSUE THREAD

**Issue by emorling** [bennycode/ig-trading-api#526]
I am trying to place a MARKET order. The createOrder just freezes, and doesn't return an error. So I'm not sure what's happening.

Is it not possible to place a MARKET order type? I noticed its not in the OrderType interface.
I also noticed that level is obligatory for your createOrderResponse method, but the iG documentation states that MARKET orders should not have a level.

Any help is welcome. 

```
 const client = new APIClient(APIClient.URL_DEMO, apiKey);
  const session = await client.rest.login.createSession(username, password);
  console.info(`Your client ID is "${session.clientId}".`);

  const createOrderResponse = await client.rest.dealing.createOrder({
    epic: 'CS.D.EURUSD.MINI.IP',
    expiry: '-', // null as it's a DFB (daily funded bet)
    direction: 'BUY',
    size: 1,
    type: 'MARKET',
    guaranteedStop: false,
    timeInForce: 'FILL_OR_KILL',
    stopDistance: 20, // 20 pips stop loss
    forceOpen: true, // Force open is true since we have a stop distance
    currencyCode: 'EUR', // Set the currency
    level: null,
  });
  console.log(createOrderResponse);
```

**Comment by bennycode** [comment]
Hi @emorling, can you link the documentation about IG's market orders? I can only see `LIMIT` and `STOP` for `orderType` on https://labs.ig.com/rest-trading-api-reference/service-detail?id=692.

**Comment by bennycode** [comment]
Closing because no repsonse.
