### ISSUE TITLE
Exposing types in package

### ISSUE THREAD

**Issue by loadpixels** [bennycode/ig-trading-api#56]
Hi again - I was wondering about exposing some types to dependent projects - stuff like `MarketDetails` or `CandleStick` for example are useful when you want to expect a specific type in a class constructor etc. I'm happy to do the work and pull request to expose them, but beyond putting explicit `export { MarketDetail } from './MarketAPI';` on `index.ts` I'm not really sure how best to go about it.

If you're interested in the idea and can give me some pointers I'll submit a PR

**Comment by bennycode** [comment]
Oh, that slipped through the cracks! 🙈 

I just added a [barrel export](https://basarat.gitbook.io/typescript/main-1/barrel) to [expose the relevant enums and interfaces](https://github.com/bennycode/ig-trading-api/pull/57).

You can use it now like this:

```ts
import {CandleStick} from 'ig-trading-api';

const candleStick: CandleStick = {}; // ...
```
