### ISSUE TITLE
Some code samples should be great

### ISSUE THREAD

**Issue by franck34** [bennycode/ig-trading-api#610]
Hi !

Thank for this great job.

The doc is very technical : it's hard to find things before going deeper

Wondering if you can add some code sample, i.e

* search for an epic (get the epic code)
* subscribe to ticks of an epic
* get history candles of an epic

I think, in a first time, that most people want to do.

Cheers !

**Comment by franck34** [comment]
Let me PR.

**Comment by franck34** [comment]
@bennycode btw, your code is really really clean man, congrats !

**Comment by franck34** [comment]
See PR https://github.com/bennycode/ig-trading-api/pull/614

**Comment by bennycode** [comment]
Thanks for your PR! The README is updated now. You can also find many code examples here: https://github.com/bennycode/ig-trading-api/tree/main/src/demo

Best,
Benny
