### ISSUE TITLE
error handling: subscribeCandle bad resolution should throw an error

### ISSUE THREAD

**Issue by franck34** [bennycode/ig-trading-api#616]
```
const epics = [  'IX.D.DAX.OPTCALL.IP' ];

client.stream.subscribeCandles(epics, "**incorrect resolution**", (epic, candle) => { console.log('minute', JSON.stringify(candle, null, 4)); });
```

will throw an error as expected, coming from IG api (i suppose)
```
node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
{
  name: 'IllegalArgumentException',
  message: 'An item name cannot contain spaces'
}
```

But 

```
const epics = [  'IX.D.DAX.OPTCALL.IP' ];

client.stream.subscribeCandles(epics, "**incorrectresolution**", (epic, candle) => { console.log('minute', JSON.stringify(candle, null, 4)); });
```

no error throwed. It should.

**Comment by bennycode** [comment]
Hi @franck34, are you using the code with TypeScript? If using TypeScript, it will be impossible to supply incorrect resolutions:

![image](https://github.com/bennycode/ig-trading-api/assets/469989/2a8d5705-e679-4e97-a2ac-48237db36db6)

**Comment by eviltik** [comment]
What if i dev with vim ? you have to add some integrity checks.

**Comment by bennycode** [comment]
> What if i dev with vim ? you have to add some integrity checks.

This TypeScript library is designed for optimal performance with type checking, ensuring a seamless and efficient experience when used as intended. If you use it without type checking, you do so at your own risk and off-label use.

**Comment by eviltik** [comment]
interesting point of view. What if i pass the variable trought a parameter ? i have to check myself before passing it to your lib ? if you don't check parameters, your lib is vuln.
